name: ibc-tf3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.9.9
  - certifi=2024.8.30
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.3
  - pthread-stubs=0.3
  - python=3.9.0
  - readline=8.3
  - setuptools=65.6.3
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.38.4
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==0.12.0
      - asciitree==0.3.3
      - astunparse==1.6.3
      - backcall==0.2.0
      - cached-property==1.5.2
      - cachetools==5.5.2
      - charset-normalizer==3.4.3
      - clang==5.0
      - cloudpickle==2.2.1
      - cycler==0.11.0
      - debugpy==1.5.1
      - decorator==5.1.1
      - dm-tree==0.1.8
      - entrypoints==0.4
      - fasteners==0.20
      - flatbuffers==1.12
      - gast==0.4.0
      - gin-config==0.4.0
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.62.3
      - gym==0.23.0
      - gym-notices==0.1.0
      - h5py==3.1.0
      - idna==3.10
      - importlib-metadata==6.7.0
      - ipython==7.34.0
      - jedi==0.19.2
      - keras==2.6.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.4.3
      - matplotlib-inline==0.1.6
      - mediapy==1.0.3
      - numcodecs==0.10.2
      - numpy==1.19.5
      - oauthlib==3.2.2
      - opencv-python==4.5.3.56
      - opt-einsum==3.3.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==24.0
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybullet==3.1.6
      - pygments==2.17.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scipy==1.7.1
      - six==1.15.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.6.0
      - tensorflow-estimator==2.15.0
      - tensorflow-probability==0.14.1
      - termcolor==1.1.0
      - tf-agents==0.11.0rc0
      - tqdm==4.62.2
      - traitlets==5.9.0
      - typing-extensions==3.7.4.3
      - urllib3==2.0.7
      - wcwidth==0.2.13
      - werkzeug==2.2.3
      - wrapt==1.12.1
      - zarr==2.12.0
      - zipp==3.15.0
prefix: /home/ps/anaconda3/envs/ibc-tf
